### ISSUE TITLE
Track when an effort was undertaken by multiple people

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#103]
As the race director, I'm trying to encourage community among FLRC Challenge participants, and one way of doing that is to encourage people to run together. I'm also trying to make the Challenge more inclusive at the prize level, and rewarding runners for community-promoting behavior would be one way to do that. 

What I'm looking for is a way to identify when people have run together, and to award a "community point" to each person who does that (ie, all three people in a three-person run). 

Acceptance criteria:
* Group runs could be identified automatically by sufficiently close time-stamping of results that are auto-submitted via QR code.
* For manual submission of results, there could be a "Group run" checkbox that each person could select.
* Community points could be tracked on the main page alongside Most Points for men and women, and on a separate page.

**Comment by SteveDesmond-ca** [comment]
Is there a limit to how many community points someone can earn at a time?

My thought would be one per course per day for each of three types. That way, for example a pair running a 2 miles on a track together isn't worth more than a Treman group run.

**Comment by adamengst** [comment]
Yes, that matches with my thinking. That way you could go on a Brooktondale group run (1 point), get breakfast with the group after (1 point), and link to a photo of the group (1). So 3 points per person would be the max per run.

I guess multiple people could share the same photo, but I think that's OK—the goal is to increase Yogile usage, and if people are finding the photo and sharing it, that's good enough.

**Comment by adamengst** [comment]
We may have to play with this a little once it's live to see that it matches with what feels right. At the moment, my thinking is that start time is really all that's important. For instance, Heather's group runs often collect 10 people or so, but unless someone comes who's her speed, she'd end up running alone and not getting credit. 

As for the window, my inclination is to make it a bit wider—maybe 15 minutes. That way, manual timing people could get back to their cars, get their phones, and all enter at the same time without having to stress about it. If we were doing Heather's run, for instance, I would then clock in with you at the end, rather muck with the phone at the start.

**Comment by SteveDesmond-ca** [comment]
Looking at some random days from our [most popular course from last year](https://2021.challenge.fingerlakesrunners.org/Log/All/235658/) 5 minutes is probably a better starting point to balance minimizing false positives with allowing plenty of time for removing any "manual sync" anxiety.

**Comment by SteveDesmond-ca** [comment]
Things are looking good: the system can now determine which results are part of a "group run" which are displayed as runner emoji on any "activity log" style page in a new "Community" column (narrative and local business points will show up as separate emoji here as well).

Here's one from a Saturday morning group run:
![image](https://user-images.githubusercontent.com/195896/162013562-3930e4f4-baad-4c6b-a337-9ad9b3661c4f.png)

And when it's just a pair:
![image](https://user-images.githubusercontent.com/195896/162013758-0283653d-0af4-4dc8-87fd-5421bb83de0d.png)

Next up, scoring/points!

**Comment by SteveDesmond-ca** [comment]
Interesting find now that community points are being scored: the top 6 for last year (which technically only had "group run" points) are all couples
![image](https://user-images.githubusercontent.com/195896/162445023-8b74e0a2-914c-4c7d-b7f7-73d335bebf51.png)

My assumption is that formally incentivizing running together will help even this out among non-partners, but just a heads up in case there's any hint of bias (ala "married filing jointly => tax break") that might need some messaging prepped ahead of the competition.

**Comment by SteveDesmond-ca** [comment]
Or just don't count it as a match if the other person has the same last name :sweat_smile:

**Comment by adamengst** [comment]
I guess we're a more traditional group here in Ithaca than one might think, with these married couples all having the same last name. ;-)

**Comment by SteveDesmond-ca** [comment]
Implemented as of 855d8ad
