### ISSUE TITLE
Update team age calculation date to April 16th, 2022

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#107]
Since we're running from April 16th through August 14th, we can start the team age calculation on April 16th, 2022 rather than January 1st.

**Comment by SteveDesmond-ca** [comment]
:tada: It looks like we're pulling the age directly from WebScorer, which uses the competition start date and the user's birthdate, so as long as the real events in WebScorer use the right start date (4/16-8/14), this will work.

Note that the [test event](https://www.webscorer.com/register?pid=1&raceid=270969) has a Jan 1 start date, so ages will be off for those of us born between Jan 1 and 4/16.
