### ISSUE TITLE
Page listing prize amounts

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#108]
As the race director, I spent a rather insane amount of time copying names into a spreadsheet to calculate how much everyone won. It would be great if there was a page that would simply report on that to save the work, particularly since we'll need to do it quickly after the Challenge ends and before the award ceremony 11 days later.

Also, as a runner, I might want to see how much I'm likely to win if I maintain a position or improve.

See the spreadsheet I built for this last year....

https://docs.google.com/spreadsheets/d/1AojvdFqT6fTiIhRPb32-n4Yr1n9g60uNhTC77t7uKwQ/edit?usp=sharing

**Comment by SteveDesmond-ca** [comment]
I made a lot of progress on this this morning, with just one somewhat complex edge case remaining.

Looking at [Forest Frolic last year](https://2021.challenge.fingerlakesrunners.org/Course/237877/Fastest/F/):
- the 1-29 F age group only has 1 winner, despite there being 2 identical times, because the other identical time won the overall fastest course time (F) award due to the age grade tiebreaker
- the 60+ F age group has 2 winners, because they had the same time

So, here's my understanding based on last year's awards:
- for "overall fastest course time (M/F)" awards, we include the age grade tiebreaker, so there's only 1 winner, and the other gets the age group award (unless 2 people who are the same age run the same time, then they'd both get it, and the age group award would go to the next person)
- for "age group" awards, we ignore the age grade tiebreaker: everyone in that age group who runs the fastest time gets it

**Comment by SteveDesmond-ca** [comment]
Actually hold on, something else isn't right...I was looking at the wrong page. Did Jullien get missed / left off, perhaps because of the hidden note on the right of the awards spreadsheet?

**Comment by adamengst** [comment]
The Age Group pop-up menu isn't working for me on the 2021 Frolic page—it just loads the same data as before, but I see what you're saying about Gabby and Jullien. I believe I just missed that when doing the prizes, so Jullien lost out on $5. (The hidden note was unrelated; I had initially sent her a check before the end of the year to get expenses into one year, not realizing that Margaret would win on the last day. Very embarrassing.)

The rules don't talk about what to do in case of ties, but In the two cases where there were actual ties (Most Miles and per-course age groups), I awarded identical prizes. So I think that should probably carry over to the overall fastest course time awards—if there is a legitimate tie, both people should win rather than there being a tiebreaker. 

And once we figure this out, I'll update the rules!

**Comment by SteveDesmond-ca** [comment]
Yeah, the age group dropdown was a known issue of the scrape. Another example of the same thing I just found was Klaas and Keith for 60+ M at Cornell Botanic Gardens.

The last thing left then is the determination of top 10 team members, which doesn't match the ranking on the leaderboard. I remember we talked about a potential "scoring" algorithm in #54, but nothing was ever implemented -- how did you come up with the top 10 for team 30-39 last year? We'll need to update the ranking of the team member page accordingly.

**Comment by adamengst** [comment]
Right, the top 10 team members list was a fuzzy, hand-coded set. The issue was that I needed a way to reward people like Heather, who contributed a lot of miles, but who weren't in the age-grade list. Can you think of an algorithm that weights age-grade contributions and most miles contributions equally, and then creates a list from that set? Perhaps like XC scoring, where the top 10 in each category get their number of points, both are added, and then the top 10 lowest combined get prizes, just like the team competition itself?

**Comment by SteveDesmond-ca** [comment]
Yes, that makes sense, I'll see what I can come up with tomorrow!

**Comment by SteveDesmond-ca** [comment]
Will the "Community Stars" winner / top X get awards? If so, same as the other non-gendered overall ones?

**Comment by SteveDesmond-ca** [comment]
I played around with various scoring and algorithms for the "top 10 team members" this afternoon, and to get closest to your list from 2021, here's what I figured out:

Team members will now have a "score" which is their average age grade plus the number of marathons they have run as part of the challenge.
![image](https://user-images.githubusercontent.com/195896/164553827-057fbf32-d538-4cc4-8de8-b6db371bd549.png)
A marathon was a good round number (:sweat_smile:), but any interval from 3 to 47 miles gives the same top 10 as you picked last year, though anything less than a marathon seems to lean too heavily on raw mileage.

The main advantage of this over the cross-country style scoring is that it promotes continued effort throughout the challenge -- your score still increases as you run more or faster, even if you're already in 1st place for that metric, vs you can't get a lower XC score than 1 in either category. Similarly, if you're in 2nd but have a long way to go until 1st, you can slowly catch up vs not seeing any change until you surpass the next person.

Thoughts?

**Comment by SteveDesmond-ca** [comment]
I updated the "score" for completeness/fairness/consistency to include courses run as the primary metric (otherwise someone fast was in 12th place last year despite only completing 7 courses) and total runs, so that those running lots of short courses aren't at a disadvantage for not putting in the raw miles.

So the score is now the sum of:
- 50 for every unique course run (up to 500)
- 1 for every age grade percent (up to 100, pro-rated)
- 1 for every 50 runs (unlimited, pro-rated)
- 1 for every 26.2 miles (unlimited, pro-rated)

![image](https://user-images.githubusercontent.com/195896/164721941-936b45d0-ce7c-40b9-b74f-9472507b72a6.png)

We may need to still tweak the algorithm as we go, since this year's competition is less than half as long as last year, calendar-wise, but now that the basics are all in place, that should be pretty straightforward.

**Comment by adamengst** [comment]
I like that—it gives us both the top 10 we need and shows how valuable they are (or can be) for the team.

**Comment by SteveDesmond-ca** [comment]
Implemented as of 2e8bccd -- I fully reconciled the 2021 awards against the spreadsheet (with the caveats we discussed above) so I'm 99% confident in its accuracy.

The awards page is currently available at https://challenge.fingerlakesrunners.org/awards, but I haven't added it to the "Reports" menu (wasn't sure if we wanted to make it "public" yet) -- feel free to open a new issue for this feature if/when you think it's ready!

Note that the amounts are [configurable per award type](https://github.com/FingerLakesRunnersClub/Leaderboards/blob/main/Challenge/appsettings.json#L43-L59), but are static values -- same as above, let me know via a new issue with the new values if we should reduce these, given current participant numbers.

**Comment by adamengst** [comment]
Could you link the athlete names to their pages, so it's a little easier to cross-check? The results didn't make a lot of sense to me until I realized that there were so many ties currently that everything is confusing.

I think we should indeed hold on releasing this until the numbers have started to settle down.

**Comment by SteveDesmond-ca** [comment]
:100: good idea, I also added links to each award in c4df6a3 just now (currently deploying) pointing to the relevant results table

**Comment by adamengst** [comment]
Totally forgot about this page! Can you remind me what multiplier it’s using for the Total column, which I think is the amount of money people win? I need to make sure that matches with the number of runners this year.

**Comment by adamengst** [comment]
Actually, the real variable may be just the number of runners, which we should set to 160 this year for even numbers. (It’s actually 159.)

**Comment by SteveDesmond-ca** [comment]
The "awards" section of the app settings contain the award amounts, no fancy multiplier just the actual dollar value.

https://github.com/FingerLakesRunnersClub/Leaderboards/blob/main/Challenge/appsettings.json#L44

Feel free to edit that file directly in the GitHub UI, or let me know the final amounts, and I can deploy a new version with the updates.

**Comment by adamengst** [comment]
Aha! Great, I’ll edit later today. Parkrun now.

**Comment by adamengst** [comment]
OK, two requests:

* Could you add a $ before the numbers in the Total column to clarify that people are winning gift certificates?
* Could you then redeploy so it picks up the new award amounts ($80, $8, $4, based on last year's multipliers)?

Thanks!

**Comment by SteveDesmond-ca** [comment]
Implemented as of 255376c

**Comment by SteveDesmond-ca** [comment]
(currency symbol is currently not showing correctly, investigating)

**Comment by adamengst** [comment]
Oh, and can you add a link to Awards in the Reports menu? Thanks!

**Comment by SteveDesmond-ca** [comment]
Completed as of 9ff1e8b
