### ISSUE TITLE
Link up new Webscorer results pages with the 2022 leaderboard

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#110]
I have recorded some fake results for each race today, so these should be the Webscorer result page IDs:

Sweet 1600: 273395
Lansing Center: 273396
Beebe Lake: 273397
Taughannock: 273398
Long Loomis: 273399
Inlet Shore: 273400
East Hill Dryden Rail Trail: 273401
Jim Schug Trail: 273402
Brookton Hill & Dale: 273403
Lick Brook Treman: 273404

I'm a little worried that if no one runs one of these courses for a week, the IDs will change again. I recorded a result for each of these on April 9th, but Webscorer still made a new results file for each one today. I could record fake results again mid-week for courses that haven't gotten traffic if necessary.

**Comment by adamengst** [comment]
Hmm. Or maybe it's related to the fact that I keep changing the open date to be able to record times. I'll leave it set to today and if anyone else records a time today, I'll delete it manually. :-)

**Comment by SteveDesmond-ca** [comment]
Thanks, I was just about to send a message about this -- could you create the forum threads for each course as well? I should be able to get the config completed tonight for go-live tomorrow!

**Comment by adamengst** [comment]
Great minds... I've done one forum thread—take a look and if that's good, I'll do the rest in the same way. I presume there are IDs involved, so the actual names don't matter?

**Comment by SteveDesmond-ca** [comment]
Correct, I just need the auto-incrementing topic ID for each course to add to the leaderboard config (3183 in this case)

**Comment by adamengst** [comment]
And those are all done now.

**Comment by adamengst** [comment]
Here's a list. Just Beebe Lake out of sequence. I knew I should have started with Sweet 1600!

Sweet 1600: 3184
Lansing Center: 3185
Beebe Lake: 3183
Taughannock: 3186
Long Loomis: 3187
Inlet Shore: 3188
East Hill Dryden Rail Trail: 3189
Jim Schug Trail: 3190
Brookton Hill & Dale: 3191
Lick Brook Treman: 3192

**Comment by SteveDesmond-ca** [comment]
Challenge config has been updated and is currently deploying.

The only thing left is the race ID for the start list, which if I recall from last year is different from the series confirmation list -- any idea what that is? Last year it was 230581, if that helps at all...

**Comment by adamengst** [comment]
Nice running with you this morning!

Last year, we used the raceID for the East Hill Rec Way. This year, if you want a raceID, here's the one from Sweet 1600.

https://www.webscorer.com/members/myracedetails?raceid=271794

If you want to try the series registration, it's a similar ID, but may not look up in the same way because it's a seriesID:

https://www.webscorer.com/members/regseriesinfo?seriesid=271797

**Comment by SteveDesmond-ca** [comment]
:100: the 1600 race ID worked -- now just to remember that for next year! :sweat_smile:

Implemented as of 27aafd3
