### ISSUE TITLE
Age Grade not showing for Sweet 1600 course

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#111]
There's no Age Grade showing for my Sweet 1600 efforts today. I wonder if it's just not in our lookup table?

![image](https://user-images.githubusercontent.com/36641103/163882198-5a43e8c8-07b0-406a-a029-2e3cc75e77f4.png)

**Comment by SteveDesmond-ca** [comment]
Ahh, it's less than a mile, so there's no official way to age grade it -- my recommendation would be to make the distance in the system 1 mile

**Comment by adamengst** [comment]
Sure, let's do that. It's a funky distance and it's better to equate it to the mile than try to estimate up from the 1500. We'll just look a little better!

**Comment by SteveDesmond-ca** [comment]
Implemented in 6c5b9c7
