### ISSUE TITLE
Community stars from Discourse seem to be getting stuck

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#115]
If you look at the Activity Log and compare against the Star Posts in the forum. None of the Story or Shop Local posts from today's Taughannock run are showing up.

Heather's post on 4/30 from Brookton Hill & Dale is the last one to get either of those stars.

**Comment by SteveDesmond-ca** [comment]
Yep, I just saw this when posting mine -- the default Discourse API endpoint only shows 20 posts per topic, so none of the newer Taughannock ones are showing up...I'll figure it out tonight!

**Comment by SteveDesmond-ca** [comment]
Implemented in 68beee1
