### ISSUE TITLE
How to handle avg age grade for small 1-29 team

### ISSUE THREAD

**Issue by SteveDesmond-ca** [FingerLakesRunnersClub/Leaderboards#119]
I noticed the 1-29 team is rather small this year, which may give an unintended advantage with the "average age grade" team score calculation.

Options, in probably order of fairness:
- leave it as is, with the assumption that their boosted age grade points will compensate for their low mileage points
- reduce the number of athletes in a team's avg age grade calculation for a course to the team with the least number of runners (so e.g. for 1600 this year, right now only top 2 from each team count towards their avg age grade, since only 2 1-29 runners have run it)
- merge the 1-29 and 30-39 teams (probably not ideal since 30-39 is already the biggest)

**Comment by SteveDesmond-ca** [comment]
Just checked to see that this is still an issue as we're meeting the end, but the only course that's really affected is Treman since that's the only one where 1-29 isn't in last for age grade anyway.

I think the best solution (other than just ignoring it😅) may actually be to fill in the missing age grades with 0's, so e.g. for the mile, they'd have the 7 fastest age grades that were actually run, and then add 3 0's to make 10 records.

We're doing something similar elsewhere in some scoring algorithm, but can't remember exactly where. Thoughts @adamengst?

**Comment by adamengst** [comment]
Given that it's clearly not going to affect anything, I'm cool with just leaving it be. But I tend to agree with you that filling in the missing records with 0's is the best option, since that's the negative that should cause the team to encourage more completions.

**Comment by SteveDesmond-ca** [comment]
Implemented in 6806539 -- no visible change as team 1-29 already dropped to last on Treman
