### ISSUE TITLE
Name changes from Webscorer not coming through to the leaderboard

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#121]
In Webscorer, I changed the registrations for "Kathryn Gannon" to "Katie Gannon" and "Gillian Hainessharp" to "Gill Haines-Sharp" to match Discourse (and their preferred spellings), but even though everything in Webscorer seems updated, the leaderboard isn't reflecting the new names, which is preventing Gill's post on Lick Brook from matching up. Not sure what's up—caching?

**Comment by SteveDesmond-ca** [comment]
Yeah, athlete info is statically cached for the duration of the app's lifetime, as it's not expected to change post-registration, so the container needs to be restarted whenever something there changes. I just did that and see the name changes, but still no Treman community points, so I'll debug that part shortly.

**Comment by SteveDesmond-ca** [comment]
Looks like the post in question doesn't have the `## Story` header, so once that's added it should come through.

**Comment by adamengst** [comment]
Thanks—I’ll ping Gill to fix.

**Comment by adamengst** [comment]
@SteveDesmond-ca Could you restart the container to see if that brings in the name changes I made in Webscorer for a few people in the Sweet 1600 registration so we can see if I need to change names in the other races as well?

**Comment by SteveDesmond-ca** [comment]
Container restarted as part of the deployment of #199, 4 users ready to be sync'd at https://challenge.fingerlakesrunners.org/Community/Admin

**Comment by adamengst** [comment]
Seems to have worked perfectly, thanks!
