### ISSUE TITLE
Archive 2022 Challenge leaderboard

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#142]
As someone who participated in the 2022 FLRC Challenge, I'd like to be able to see my results from that year, so it would be great if we could archive the leaderboard by turning it into static files like we did for 2021. It can have its own 2022.challenge.fingerlakesrunners.org domain.

Thanks!

**Comment by SteveDesmond-ca** [comment]
The 2022 Challenge Leaderboard is now available at https://2022.challenge.fingerlakesrunners.org/ -- with same caveats as before: the per-course age group filter (and months, since it uses the same server-side query string logic) aren't able to be archived
