### ISSUE TITLE
Remove per-month filters and UI from 2023 leaderboard

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#143]
Even as someone who followed the leaderboard closely, I didn't find that the month filters were all that interesting. The data was just too random, and people didn't get into it. So let's remove them entirely and just show the cumulative data to the current date as we did in 2021.

**Comment by SteveDesmond-ca** [comment]
:tada: Looks like past me was smart enough to include a feature toggle for this, probably to differentiate between the Challenge and Trail Circuit, so I just turned it off in 9eccdfd (the underlying code can be removed as its found) -- it'll go out with the first deploy, once 2023 course information is setup...can you create a new issue with course names and race IDs, once they're entered?

**Comment by SteveDesmond-ca** [comment]
Disabled code removed in bbdeab3
