### ISSUE TITLE
Add the option to hide individual results on the leaderboard

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#144]
As someone who's really shy and slow, I want to be able to participate in the Challenge without anyone seeing what I'm running. 

As the race director, I want to enable such people to participate. To that end, I've added a question whose YES/NO answer will come through in a field called Info2. It currently reads:

> Do you wish to hide your individual runs on the leaderboard and not compete for anything but a completion medal? (You'll still appear in the participant and completion lists.)

My current thinking is that these people would appear in the list of participants and, if they completed all 10 courses, the completion list. However, their runs wouldn't show up in the activity log overall or for any course. Nor would they appear in the leaderboard lists for any competition. 

What I can't quite decide about is the Athlete page. Since we have no logins, it's public, but if we don't show it, then they have no way of checking what they've done. My sense for now is to show it. Perhaps the page could be grayed-out by default, with a CSS button that would read "I am Joe Schmoe" and clicking it would display everything. That way it's there, but other people wouldn't likely look much. 

Thoughts welcome!

**Comment by SteveDesmond-ca** [comment]
It's really about what scenarios this is trying to support.

I think the most basic change would be to just not "Rank" anyone with this flag, so they'd still show up on the activity log (without a time?) and their athlete page could show their total runs, etc. We'd still want those runs to count towards the total runs/miles in statistics, and theoretically could also count towards top team miles, too.

On the other extreme is like you're talking about: show nothing except that they're a participant and that they completed all courses. I think anything we don't show can't be counted towards teams/totals, as someone "auditing" the data wouldn't be able to reconcile what they're seeing with what the app is saying.

**Comment by adamengst** [comment]
I'll admit that I'm having trouble imagining what these people really want, since they're shy enough that I'm seldom getting the request directly, but usually through a friend who tried to recruit them. Let me see if I can start an email discussion about that.

**Comment by SteveDesmond-ca** [comment]
Made some good progress on this today, but there are _a lot_ of places where it was expected someone would have a time or age grade, so it's taking a bit find and get through them all.

**Comment by SteveDesmond-ca** [comment]
Implemented in 7dbae92, will be deployed with the 2023 course config

**Comment by SteveDesmond-ca** [comment]
Do you have any way to easily see in WebScorer if anyone has selected this option yet? Everyone in the API has an `Info2` of `""` (empty string) whereas I would have expected `"NO"` for them, based on the initial spec.

**Comment by adamengst** [comment]
These four have Y, everyone else is N

Jessica Daily
Malte Ziewitz
Melissa Plank
Heather Cobb

**Comment by adamengst** [comment]
Oh! There's a custom name I set in the question, so it may be called `Private` instead of `Info2`

**Comment by SteveDesmond-ca** [comment]
Unfortunately not seeing that in the API... Would removing/resetting the
custom name to Info2 mess up existing registrations?

**Comment by adamengst** [comment]
I've removed the "Alt download header" but now in the downloaded Excel file, that column is titled with the full text of the question. So if it's not `Info2` (could there be a space, as in `Info 2`?), we'll have to check with Vesa tomorrow.

**Comment by SteveDesmond-ca** [comment]
As of this morning, everyone still has a blank `Info2`, and no yes/no data in any other field

**Comment by SteveDesmond-ca** [comment]
WebScorer field mapping has been set, and this feature has been updated accordingly in 9ab73fb
