### ISSUE TITLE
2023 course names and race IDs

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#147]
Just starting this as a placeholder. I have things mostly set up in Webscorer, but as I remember, I have to record a result to get the raceID for the results page, and that has to happen fairly close to opening time so Webscorer doesn't age it out.

Here's the list of course names, if that's useful earlier.

Sweet 1600
Ellis Hollow Creek Crossings
Lakefront Loops 5K
Lime Hollow
Six Mile Creek
Cornell Scenic Circuit
Blueberry Patch
Black Diamond Park to Park
Ludlowville Loop
Dryden Lake Lollipop

**Comment by SteveDesmond-ca** [comment]
Here's the full list of required fields:
```
  "Races": [ 
         { 
           "Source": "WebScorer", 
           "ID": 273395, 
           "Name": "Sweet 1600", 
           "Type": "Track", 
           "Distance": "1 mile", 
           "Courses": { 
                 "Default": 273395 
           }, 
           "URL": "https://fingerlakesrunners.org/challenge/sweet-1600", 
           "CommunityID": 3184 
         },
          ...
```
`ID` and `Default` are the WebScorer results race ID, and `CommunityID`is the forum topic ID for that course's star posts. Feel free to update `Challenge/appsettings.json`directly!

**Comment by SteveDesmond-ca** [comment]
Ooh, also, in the past, we've used the "start list" ID for the 1600 as our participant list, so that too!

**Comment by SteveDesmond-ca** [comment]
@adamengst I'm not seeing any commits in the past few days. Did you `git clone` locally and forget to push your changes?

**Comment by SteveDesmond-ca** [comment]
@adamengst I see now, the file changes were made directly on the server -- I'll get that into the committed code and deployed later today.

**Comment by adamengst** [comment]
Oops, sorry, I misunderstood and just edited the `/Challenge/appsettings.json` file directly on the server using nano. I've now copied all those changes out and updated the file here in GitHub.

**Comment by adamengst** [comment]
Note that there’s one small change from what was on the server that I fixed in the GitHub version. I had forgotten to update the URL for the Dryden Lake Lollipop Course.

**Comment by SteveDesmond-ca** [comment]
💯 thanks, I'll just use what was committed and give it a once over before deploying this afternoon

**Comment by SteveDesmond-ca** [comment]
Looks mostly good, the only thing left is the participant list, which historically has come from the start list ID of the 1600/mile -- I believe this is different from the results ID, according to #42/#110, but I can't determine from WebScorer's site what that should be. Not sure if you can see it from the admin side of things, or if something changed on their end from a logic perspective, if it's worth checking with Vesa if you can't figure it out?

Also a couple people jumping the gun with Sweet 1600 results already :sweat_smile:

**Comment by adamengst** [comment]
My fault, I think. I used the results ID rather than the registration ID, which is 308700. I've updated appsettings.json and committed.

**Comment by SteveDesmond-ca** [comment]
Yep, that's it -- deploying 2023 leaderboard now!
