### ISSUE TITLE
Config file for Personal Challenge completions?

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#160]
As the Challenge director, I'd like to be able to include the kids who have completed their Personal Challenge in the Completions report on the leaderboard. Since they by definition aren't running 10 courses, the leaderboard doesn't automatically list them, which isn't ideal for them (they don't get the same public exposure for their achievement) and slightly confusing for me.

Would it be easy to add a config file in which I could enter the name of the runner and the date they finished and have the Completions page weave those results into the rest?

If it's not really easy, or if you're busy, it's not worth doing this year. :-)

**Comment by SteveDesmond-ca** [comment]
I'll see what I can whip up later today. At the very least, we can have a separate "personal completions" section on that page. Integrating it into the existing list may be too much for this year, but I don't remember exactly how that calculation is done.

If you can email me a list of names and dates, I'll turn it into a JSON file that can be uploaded next to the others.

**Comment by adamengst** [comment]
Thanks! Looks like it's just three names for now:

Simon Woods: 8 July
Elizabeth Brown: 8 July
Erin Pietras: 22 July

**Comment by SteveDesmond-ca** [comment]
Implemented in 652b6c0
