### ISSUE TITLE
Archive 2023 Challenge leaderboard

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#193]
As someone who participated in the 2023 FLRC Challenge, I'd like to be able to see my results from that year. It would be great if we could archive the leaderboard by turning it into static files like we did for 2021 and 2022. It can have its own 2023.challenge.fingerlakesrunners.org domain.

**Comment by SteveDesmond-ca** [comment]
💯 this was completed on Feb 5: https://2023.challenge.fingerlakesrunners.org
