### ISSUE TITLE
Create new leaderboard for 2024 Challenge

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#194]
Just starting things for this year. I have registration set up in Webscorer, but as I remember, I have to record a result to get the raceID for the results page, and that has to happen fairly close to opening time so Webscorer doesn't age it out. I'll do that the week before we open on April 20.

I can update the `appsettings.json` file with the appropriate raceIDs and Discourse post IDs here in GitHub once everything is ready.

Here's the list of course names, if that's useful earlier.

Sweet 1600
Duck Trails
Lakefront Loops 5K
Lindsay-Parsons
FH Fox
Valley Views
Treman Trailipop
Hammond Hill Hoctathon
Run Rabbit Run
Freeville Fly-In

**Comment by SteveDesmond-ca** [comment]
Course names, info links, and forum topic IDs have been updated.

Remaining tasks:
- WebScorer race IDs for each course, once an initial dummy result is added the week before the event starts
- the participant list I think we can do ahead of time, it's still set to last year's course ID of 308700 if that helps determine what we're looking for this year

**Comment by adamengst** [comment]
Hey, thanks! You found the queued star posts, I assume?  https://forum.fingerlakesrunners.org/c/queued-posts/37

It turns out that Vesa said he fixed the bug that caused the raceIDs to reset, so once I print QR codes for the signs, I'll test them and submit results, which should get us fixed raceIDs.

The participant list should come from Sweet 1660, which is race ID 346590

**Comment by SteveDesmond-ca** [comment]
Start list race ID is deploying now, so at this point it's just the individual course result race IDs left.

**Comment by adamengst** [comment]
I've added all the raceIDs in appsettings.json now, so I think we're ready to deploy.

**Comment by SteveDesmond-ca** [comment]
Completed as of 5ec62a4
