### ISSUE TITLE
New Challenge runners not being added to @Challengers or age-group @groups

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#197]
From what I can tell, the leaderboard isn't populating the Discourse @Challengers group or the specific age-group groups with new signups for the Challenge.

I had forgotten to clear those groups until now (it's what made me look), so if this is a one-time thing, perhaps we can clear those groups out and then trigger the import. I'm not entirely sure how it's designed to work.

**Comment by SteveDesmond-ca** [comment]
You'll need to go to https://challenge.fingerlakesrunners.org/Community/Admin and click the "Sync" button, as my notes say Discourse's heavy rate limiting would make a fully automated query+update solution untenable.

**Comment by adamengst** [comment]
Ah, right—I remember now! I'll clear those groups and click Sync.

**Comment by adamengst** [comment]
And it's all working as expected now.
