### ISSUE TITLE
Certain Challenge runners not being added despite fullName matches

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#198]
There are a few people who aren't syncing, and I'm not sure why. Three of them had name mismatches, so I corrected those on the forum, and everything worked. But these five match to start and still aren't syncing.

No hurry on this, but it's a puzzler at the moment.

Bill Begeal
Elizabeth Rechtin
Tristan Lambert
Verity Platt
Wendy Wolford

**Comment by SteveDesmond-ca** [comment]
@adamengst congratulations, the forum now has more than 1000 users!

Unfortunately, the way the API currently gets members is limited to 1000 results. Investigating a solution...

**Comment by adamengst** [comment]
Well, that's a second prize if I've ever heard one. :-) The challenges of success.

**Comment by SteveDesmond-ca** [comment]
Completed in cd7dd1c, deploying now
