### ISSUE TITLE
Challenge leaderboard statistics page showing a line for the week before we started

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#200]
The History table in the Statistics page is still showing a line for that spurious run that slipped through the week before we started officially, even though I've deleted it from Webscorer. Is there any way to remove that line?

https://challenge.fingerlakesrunners.org/Statistics

**Comment by SteveDesmond-ca** [comment]
From what I can see, the Lakefront Loops results still show the early run in question. Can you confirm, as there may be a different way results are being flagged as deleted these days.

**Comment by adamengst** [comment]
Phooey, you're right. I'd forgotten that there were TWO times that day, so I just deleted Dina's time and missed Paula's. All better now!
