### ISSUE TITLE
Add a leaderboard page that collects specific Ultra/Trail/Tarmac completions

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#203]
As a runner, I'd like the leaderboard to commemorate my achievement of completing one of the specific Ultra/Trail/Tarmac challenges. 

As the race director, I'd like a page that would automatically detect such accomplishments and display them in three stacked tables:

* FLRC 100K Ultra Challenge
* FLRC Tough Trail Challenge
* FLRC Tough Tarmac Challenge

Each table should list, chronologically (with earlier finishers sorted first so they get more attention), the runners who have completed the associated challenge. It should include at minimum, the runner's name, the date of completion, the time spent running, and the total elapsed time.

For the Ultra Challenge, the runner must have completed all 10 courses within 24 hours of starting.

For the other two, the runner must have completed 5 courses within 12 hours of starting.

The Tough Trail courses for this year are:

* Duck Trails
* Lindsay-Parsons
* FH Fox
* Treman Trailipop
* Hammond Hill Hoctathon

The Tough Tarmac trails for this year are:

* Sweet 1600
* Lakefront Loops 5K
* Valley Views
* Run Rabbit Run
* Freeville Fly-In 

The page should be accessible in the Reports menu under "Ultra Challenges"

**Comment by SteveDesmond-ca** [comment]
Proposed columns: 
- rank
- name
- age
- category
- start date/time
- finish date/time
- total time
- running time

Can a person appear more than once in each list? That might determine whether tables can be sorted on all columns.

**Comment by adamengst** [comment]
So "rank" would be just the order of finish, like on the Completions page? If so, that seems fine, as do all the rest.

And yes, a person could easily appear more than once—Pete has multiple completions of the Ultra Challenge in some years.

**Comment by SteveDesmond-ca** [comment]
Ooh, and I guess similarly, a successful 100K attempt could also count as one or both of the Tough T[...] challenges, right? e.g. it looks like Pete also got the trail courses done in under 12 hours on 4/20, but not the road ones.

**Comment by adamengst** [comment]
I think I'm not in favor of the 100K Ultra Challenge double-dipping on the Trail and Tarmac Challenges. It seems like it should be one or the other, partly because of prizes. However, I could see a failed 100K Ultra Challenge effort ending up with just a Trail Challenge completion.

**Comment by SteveDesmond-ca** [comment]
As I'm going through this, thinking of how to break it, there are a couple edge cases that immediately come to mind that we can probably ignore for now at least, unless you feel strongly otherwise, and the add them in later as necessary:
- someone entering results for all 10 courses manually on the same day
  > this one's not too hard to mitigate, just add a minimum time like we have for erroneous individual result submissions

- someone "re-do'ing" their first course, either at the beginning and the end -- or multiple times at the beginning -- would show up as separate completions
  > e.g. start with a mile, do the other 9 courses in distance order, then run another mile (to improve either total or running time) would show up as a completion for runs 1-10, and one for runs 2-11

  > or run 2 miles first, then the other 9 courses = one result for 1,3-11 and another for 2-11

  > What would be the logic for determining which completion to select? For the 1st case, always the first (earliest) 10 unique courses that fall within 24 hours, since that's how we'll be ranking them, and if they want credit for the extra (slower) run, they can enter it manually on a different day? The 2nd case we could just check if they run 2 (or more) of the same course in a row as their first runs and use the last one

I'm sure there will be more as I dig deeper. Thoughts on immediate importance? Maybe once I get it built I can run it through past years and see if any of these actually get triggered?

**Comment by adamengst** [comment]
Interesting edge cases, though I think they'd be extremely uncommon—people seem to be in "get it done" mode rather than trying to optimize for time. I don't think it would have triggered on any 100K Ultra Challenges—no one has ever run a second mile.

That said, it feels like we could just decree that it will always be the last set of courses that match the requirements, picking the last run of each course that meets the requirements. That should result in the fastest collection in your case of running multiple miles first, and in the case of sandwiching courses between miles, they'd get to roll the dice on whether the last mile would be faster than the first.

Does that sound right, or is there something I'm not considering?

**Comment by SteveDesmond-ca** [comment]
Progress!

![image](https://github.com/FingerLakesRunnersClub/Leaderboards/assets/195896/81fb39cc-30ef-46ad-a810-3529ed8329fd)

**Comment by adamengst** [comment]
Looking good!

**Comment by SteveDesmond-ca** [comment]
The only remaining test at this point is just re-importing previous years' configs to confirm that the results match what's expected, and then this can hopefully be deployed later this week.

**Comment by SteveDesmond-ca** [comment]
Implemented as of 8566085
