### ISSUE TITLE
Some way of marking runners who have completed the Challenge or an Ultra Challenge

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#205]
As the race director, I'd like to reward the people who have accomplished the basic goal of the Challenge, which is completing all ten courses. That's what the Completions page does, of course, but I wonder if there's a way the leaderboard could easily give people badges of some sort as well. For instance, could w add a medal emoji to their name in the Athlete page and subordinate pages where the athlete name is the primary heading for the page?

<img width="1159" alt="Arc 2024-05-18 at 11 58 35@2x" src="https://github.com/FingerLakesRunnersClub/Leaderboards/assets/36641103/f3de423c-2eaa-4afe-8fe5-fd823e235053">

Completing the various Ultra Challenges could provide additional badges to the name on the Athlete pages.

**Comment by SteveDesmond-ca** [comment]
We've got an icon library called "fontawesome" that keeps things consistent across platforms (from a design standpoint, there's unfortunately too much variance in emoji) -- implemented as of 97b87a4!
