### ISSUE TITLE
Boulderhead runner getting two FL50s distances

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#209]
Melanie Duras is showing up as the leader in the Boulder head rankings because she seems to have gotten results for both the 50 K and the 50 mile, which shouldn’t be possible. 

![IMG_1012](https://github.com/FingerLakesRunnersClub/Leaderboards/assets/36641103/e0db85ea-b484-46d3-9caf-8ffa0e049f29)

**Comment by SteveDesmond-ca** [comment]
The quick fix is to contact the FL50s RD(s) and have them correct the results, assuming they did in fact not run a 50K and 50 mile separately, and there's no double-dipping (seeing as no one else has multiple results?) -- let me know if I should also add some leaderboard logic along these lines: "if an athlete shows up in the results of more than one course for the same race (in this case, 50K and 50 miles) only use the result for their longest distance."

**Comment by adamengst** [comment]
(I’m also curious about what happens when I cc someone not in GitHub…)

Jeney, there’s a problem on the Trail Circuit leaderboard for the
Boulderhead results (most miles). The person in the lead, Melanie Duras,
has 81.1 miles because she’s listed in the FL50s results on UltraSignup for
both the 50K and the 50 mile. Steve thinks the best way to address this
would be to remove the spurious result—is that something you can do and
reupload? The real question, I suppose, is what race she actually finished.
🙂 I don’t know if anyone else is duplicated, but I don’t think so, since
no one else has 81.1 miles or 47-ish with multiple FL50s finishes.

https://trailcircuit.fingerlakesrunners.org/Overall/Miles

Thanks!

cheers… -Adam

**Comment by adamengst** [comment]
The RDs have now taken care of this, so we're all set.
