### ISSUE TITLE
2024 Personal Challenges not showing up on Completions page

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#213]
I've updated the /wp-content/uploads/challenge-personal.json file for Adrian and Joel Kresock with their athlete numbers from the URLs, and I restarted the docker container with 

docker-compose restart challenge

But the Completions page still isn't showing their Personal Challenge completions. Is there something else we need to do?

**Comment by SteveDesmond-ca** [comment]
Hmm, I'm seeing them both down there, maybe it was a WordPress caching issue?

**Comment by adamengst** [comment]
Dammit! This happened last year too, and I even waited more time than it took last year before saying something. Stupid caches. :-)
