### ISSUE TITLE
"Average Age Grade" is unclear on "Completions" page

### ISSUE THREAD

**Issue by SteveDesmond-ca** [FingerLakesRunnersClub/Leaderboards#84]
Because this page is taking the first time a person ran a course, rather than their fastest attempt, the average age grade listed is the average of these 10 initial runs, which doesn't match up with the overall "average age grade" competition.

@adamengst Is it preferred that a disclaimer is added somewhere (either in the app, or on the info site), or should we just remove this possibly-confusing column?

**Comment by adamengst** [comment]
Good thinking. Yes, let's just take it out. I was looking for a way to indicate roughly how fast someone was, so you could see that completing the Challenge was unrelated to speed, but I agree that this is more confusing than it's worth.

**Comment by SteveDesmond-ca** [comment]
Implemented as of e4cb6ee
