### ISSUE TITLE
Make it easy (but not super obvious) to get to past FLRC Challenge results

### ISSUE THREAD

**Issue by adamengst** [FingerLakesRunnersClub/Leaderboards#94]
As an FLRC Challenge runner who has competed in multiple years, I'd like to see my results from previous years so it would be nice to be able to click a link from the current year's Challenge leaderboard to get to the archived versions from past years. Perhaps in a menu or something accessible but not blatant.

(Just recording this now for when we get around to the 2022 leaderboard tweaks.)

**Comment by SteveDesmond-ca** [comment]
Implemented as of 29918a5
